### ISSUE TITLE
missing background

### ISSUE THREAD

**Issue by pyweeker** [letung3105/space-shooter-rs#1]
Hello !
could you show please how to display the background with parallax effect on clouds ?

**Comment by ltungv** [comment]
I think one option is to make separate entities for the clouds and implement systems for spawning and cleaning them up. For reference, you can take a look at how similar systems were implemented for the enemies in the game.

A spawner is a timer that send spawn events every time the timer expires.

https://github.com/letung3105/space-shooter-rs/blob/6a9ec8dc582f93b68a5087bd31eed4221cad0b48/src/systems/spawner.rs#L15-L50

The spawn events will be handled by a separate system which creates the corresponding entities.

https://github.com/letung3105/space-shooter-rs/blob/6a9ec8dc582f93b68a5087bd31eed4221cad0b48/src/entity/enemy.rs#L24-L103

The entities can be despawned once they move outside of the screen. This system can be generalized for both the clouds and the enemies by adding a tag component, if needed.

https://github.com/letung3105/space-shooter-rs/blob/6a9ec8dc582f93b68a5087bd31eed4221cad0b48/src/systems/cleanup.rs#L19-L32

**Comment by pyweeker** [comment]
thank you !!!

Le sam. 8 janv. 2022 à 17:03, Võ Lê Tùng ***@***.***> a
écrit :

**Comment by ltungv** [comment]
Btw, you can take a look at https://github.com/thetawavegame/thetawave-legacy for better overall design. It used amethyst as the engine but the ECS design that I took inspiration from is mostly the same.
